### PR TITLE
Person excluding should see exclusion of members [SQUASHED]

### PR DESCRIPTION
**Pull request by mixmix**

### CODE REVIEW

**Comment by Powersource** [comment]
From #73

**Comment by Powersource** [comment]
Applied suggestion from the other PR

**Comment by Powersource** [comment]
ready for review @mixmix (is github gonna let you? :thinking: )

**Review by mixmix — COMMENTED** [review]
yusss

**Comment by mixmix** [comment]
no idea why I couldn't "approve"
but code is good, tests are passing. MERGING

**Pull request merged**
