### PR TITLE
Pass along options given to publish

### PR DESCRIPTION
**Pull request by Powersource**
For https://github.com/ssbc/ssb-recps-guard/pull/6

### CODE REVIEW

**Review by mixmix — CHANGES_REQUESTED** [review]
# :fire:

 this would let you publish public messages through `tribes.publish`. I'm strongly opposed to that. IMO this method should never allow that. Should always require 
- EITHER `content.recps`
- OR ... nah that's it

I think it should just go:

```js
if (!content.recps) return cb(Error('tribes.publish requires content.recps)
```

**Comment by Powersource** [comment]
> this would let you publish public messages through tribes.publish

I agree that it's weird that tribes.publish can publish public stuff but that's the way it works currently (with or without this PR). There are even tests for it https://github.com/ssbc/ssb-tribes/blob/53375b95f0cbb12e38c9b1fdd9c9a70ed240705c/test/generate/group-id.js#L7

**Comment by Powersource** [comment]
hmm ok i'm not sure that file i linked actually ever gets run lol

**Comment by Powersource** [comment]
it's actually tested here, so your change suggestion breaks this test https://github.com/ssbc/ssb-tribes/blob/53375b95f0cbb12e38c9b1fdd9c9a70ed240705c/test/publish.test.js#L102

however your suggestion also sounds very tempting so i might just apply it anyway

**Review by mixmix — APPROVED** [review]

**Pull request merged**
